### ISSUE TITLE
progress?

### ISSUE THREAD

**Issue by JonathanLehner** [whatsdis/pluribus#1]
are you still working on this repo?

**Comment by fedden** [comment]
+1, I'd be interested in helping out if there is active work on this project!

**Comment by whatsdis** [comment]
@JonathanLehner @fedden hey guys I've hit a road block with the math behind the algorithm described in the paper. Largely, I don't understand some of the mathematical notations even though I googled a lot of it, I've run into some stuff which I can't figure out. 

If any of you are can help decode it, that would help start work again.

I created a gitter community here where we can coordinate: https://gitter.im/pluribus-poker/community#

**Comment by fedden** [comment]
I did reach out to you on gitter, but there was no reply there...

I wanted to let you know I'm working on an implementation [here](https://github.com/fedden/pluribus-poker-AI). I've detailed the outstanding work as best I can for now, please feel welcome to drop by!

**Comment by whatsdis** [comment]
@fedden my apologies im in the middle of releasing some other unrelated code here and have not been able to get back to you. I'm so excited you started another repo. I will definitely drop when I get some breather by end of this week.

**Comment by fedden** [comment]
Awesome thanks @whatsdis - criticsms and feedback of the approach are very welcome, feel free to get involved! Best of luck with your other endeavours 🙂

**Comment by ghost** [comment]
I'm also trying to implement it! Repo coming soon. Tip, if you don't understand the math,This is a very handy paper that introduces CFR. The algorithm is very similar (though a bit more simplified) http://modelai.gettysburg.edu/2013/cfr/index.html#objectives

**Comment by giorgosn** [comment]
@EAT-CODE-KITE-REPEAT I am waiting to see some action!
If you are looking for some help please contact with me. I can code some things!

**Comment by fedden** [comment]
Help is appreciated on my repo if you have time to drop by!

**Comment by whatsdis** [comment]
Hi @everyone!

I ported @EAT-CODE-KITE-REPEAT 's javascript implementation to Python. 

I'm going to close this issue now.
